### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by odinlake** [odinlake/tstp#1]
I'm writing this to figure out how git issue tracking works. Our review process for Voyager is invaluable and I don't think we need more issue tracking there. However, to expand the scope of stories we can't always be synchronized. It is still invaluable to have a second person review a story and that person should (imho) feel free to make changes and addition as he sees fit. But questions may arise and issue tracking could be a way to keep track of such questions without having to answer them straight away (as in slack).

**Comment by odinlake** [comment]
testing a comment

**Comment by odinlake** [comment]
once we are satisfied with an issue, it should be closed - of course.

**Comment by paul-sheridan** [comment]
I'm satisfied.
